### PR TITLE
Add EfsALG msg and topic

### PR DESCRIPTION
**Pull request by Sandruz**
The following PR will introduce the possibility to visualize the Ublox automatic IMU-mount alignment status by inspecting the `/ublox/efsalg` topic.

### CODE REVIEW

**Comment by Sandruz** [comment]
@versatran01 Can you please give me a review of this please?

**Comment by versatran01** [comment]
Looks good to me but I will let @fcladera take a closer look.

**Comment by Sandruz** [comment]
> Looks good to me but I will let @fcladera take a closer look.

Thanks, @fcladera the msg structure is based on the official Manual here:
https://content.u-blox.com/sites/default/files/M9-MDR-2.10_InterfaceDescription_UBX-21036678.pdf (Page 65)
It doesn't seems that a serializer is needed, but let me know.

**Review by fcladera — APPROVED** [review]

**Comment by fcladera** [comment]
Thanks for your PR!

**Pull request merged**
