### PR TITLE
Initial ROS 2 port to Dashing

### PR DESCRIPTION
**Pull request by clalancette**
This very large PR is an initial, lightly-tested port of this driver to ROS 2.  There's a lot to digest here, so let me take it with bullet-points:

* ~~I've targeted this PR at master, but that isn't correct.  If the maintainers can create a `dashing-devel` branch (branched off of master), then I can retarget the PR to that.~~ (this got done, thanks)
* I've switched from using `boost::asio` to the standalone `asio` library.  That shouldn't cause too many problems, but it is notable.
* I've removed the use of `ros::serialization` from the library.  More specifically, I took the parts of the ROS 1 code that implemented this and copied it into the `ublox_msgs` package.  The basic reason for this is that ROS 2 does *not* use the same serialization protocol, so we cannot re-use the serialization from ROS 2.  While the ROS 1 serialization protocol happened to be compatible with the UBlox serialization protocol, it really is a UBlox-specific thing and thus should live in this driver.
* There are ~100 commits on this branch.  The first ~80 are a refactor of the ROS 1 code so that it is easier to do the port.  The last ~20 are the ROS 2 port itself.
* It should be possible to take the first ~80 commits and merge them onto master, since the ROS 1 code still works after those commits.
* I've only tested this on ROS 2 Dashing so far.  In principle nothing used here should have changed for Eloquent, but I haven't verified yet.
* I only have a C94-M8P to test with, so that's all I've tested so far.  I also haven't tested any configurations beyond the simple "TMODE3 survey-in" one, though I will probably test more configurations in the coming days.
* ~~I still need to do some work in porting the rest of the configuration files and launch files to ROS 2.~~ (this is now done)
* We should discuss how to move forward with this very large change.  One way to go would be to take this entire chunk onto a ROS 2 branch.  Another way would be to merge the bits that make sense onto the ROS 1 branch, and reduce the difference with this port.  There may be others.

Any thoughts, comments, or questions welcome!

### CODE REVIEW

**Comment by versatran01** [comment]
Thanks for your work.
I've created a dashing-devel branch to start with.

**Comment by clalancette** [comment]
> Thanks for your work.
> I've created a dashing-devel branch to start with.

Great, thanks, I've retargeted this to the dashing-devel branch.

**Comment by versatran01** [comment]
@kartikmohta @tdinesh 
I currently don't have a GPS to test this with, and I don't have a ros2 installation to compile either.
I'm leaning towards just merging this since it is on its own branch.

**Comment by Timple** [comment]
As a third-party bystander I would actually be interested in merging the first 80 commits to the master branch.
This will
A) Increase risk of introducing bugs in ROS1
B) Reduce the risk of inital bugs in ROS2
C) Significantly reduce the effort in backporting features and fixes in a future where a majority is on ROS2

Especially C) would be a valid reason for ROS1 users to get continued support when most folks have migrated to ROS2

**Comment by versatran01** [comment]
@Timple, I agree. Would you be able to give it (the ros1 related commits) a test?

**Comment by Timple** [comment]
I could for the f9p. I'll get back at you when I performed the tests.

**Comment by kartikmohta** [comment]
> @kartikmohta @tdinesh
> I currently don't have a GPS to test this with, and I don't have a ros2 installation to compile either.
> I'm leaning towards just merging this since it is on its own branch.

@versatran01 Same issue here, I think this repository has become more popular than what we can reliably manage, we need to figure out a way to not slow down the progress others make :slightly_smiling_face:.  As @Timple pointed out, I think it would be great if the common part could be merged into the master branch and then have the remaining commits on a separate ROS2 branch.

I've given @clalancette write access to this repo as well since he seems to be doing a lot of the drivers related stuff for ROS2.

**Comment by versatran01** [comment]
@kartkmohta although I'm currently maintaining this repo, it has certainly grown beyond my ability. I think GitHub has some kind of maintainer status you can give to people. If not we could just give them write access.

**Comment by clalancette** [comment]
> Hello, how can I set the serial port on launch?

This is really the right forum for this; either an issue or a question on answers.ros.org is more appropriate.  But briefly, you set the serial port by changing the `port` parameter when you go to launch.

**Comment by clalancette** [comment]
@versatran01 @kartikmohta Friendly ping here.  I understand if you don't have time to review all of this, nor necessarily have time to test the refactor of the ROS 1.

To move forward here, may I suggest that we just merge this into the official repository on the `dashing-devel` branch?  At least that way we have a semi-official ROS 2 port of this driver.  We can then do further reviews/fixes on that branch, and still consider whether some of those changes should be migrated onto the ROS 1 branches.  Thoughts?

**Comment by versatran01** [comment]
@clalancette done.

**Comment by clalancette** [comment]
Great, thank you!

**Pull request merged**
