### PR TITLE
fixed CfgNAVX5 message generation for protocol version >= 18

### PR DESCRIPTION
**Pull request by firolino**
According specification, version number in CfgNAVX5 must be set to 2 for protocol version >= 18

### CODE REVIEW

**Comment by riebl** [comment]
I can confirm that this change is necessary for recent firmware versions. Otherwise, applying any configuration at startup fails.
Description of UBX-CFG-NAVX5 in https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf shows that the message format has not changed, i.e. CfgNAVX5.msg requires no changes, but the version field needs to be set to "2".

**Comment by versatran01** [comment]
I will merge this but just one question, why is the protocol version float?

**Comment by riebl** [comment]
Please note that this PR does not introduce the protocol version but just loops it through. Originally, the protocol version is initialized as float in node.cpp by string conversion with `atof`.

**Comment by firolino** [comment]
Thanks!

**Pull request merged**
