### PR TITLE
fix signs of sensor_msgs::Imu output

### PR DESCRIPTION
**Pull request by riebl**
According to https://www.ros.org/reps/rep-0145.html:

> When the device is at rest, the vector will represent the specific force solely due to gravity. I.e. if the body z axis points upwards, its z axis should indicate +g. This data must be in m/s^2.

Raw data from u-blox (checked with M8U) reports -g when device's z-axis points upwards.

### CODE REVIEW

**Comment by Timple** [comment]
From threads I read in the past I think converting from from NED to ENU is more work than flipping a single axis.
For example this PR where they do a similar conversion: https://github.com/mavlink/mavros/pull/317. Because a different frame convention might also mean the orientations are wrong etc. (Also ROS answer [here](https://answers.ros.org/question/336814/how-to-change-ned-to-enu/?answer=336939#post-id-336939))

Note: I am not saying the imu is correctly implemented now, nor that your solution is incorrect. I just want to make sure that whomever reviews this is aware of the caveats.

**Comment by riebl** [comment]
You @Timple are right, there is still something fishy. When I rotate the x-axis upwards, I read -g on it but would expect +g. I have just recorded a data set with a M8U attached to a vehicle with its x-axis oriented in driving direction: for increasing speed, a negative linear acceleration is reported. That's not quite what I would expect...
I will check the `data_sign` stuff in the code now.

**Comment by flynneva** [comment]
I think I ran into the same issue and tried to make a PR to fix it but it was never approved.
#39

**Comment by riebl** [comment]
Thanks @flynneva for your hint regarding sign extension. Actually, you can get rid of the `data_sign` entirely by shifting the 24 bits of the data field to the left end and back 8 bits. Does not even require any conditionals :-)

I have just checked my change with a M8U and its published sensor data (linear_acceleration and angular_velocity) look good. Signs match the axes printed on the device's label. Magnitudes look reasonable as well. Any objections @Timple?

**Comment by Timple** [comment]
I'm not a maintainer of this package, we do however use this package (and the heading functionality) hence my interest.
I'm going to leave this review to the maintainers, perhaps @MCFurry has any insights since he did the initial implementation (#64) of the imu.

**Comment by MCFurry** [comment]
> I'm not a maintainer of this package, we do however use this package (and the heading functionality) hence my interest.
> I'm going to leave this review to the maintainers, perhaps @MCFurry has any insights since he did the initial implementation (#64) of the imu.

I did that for the F9P indeed which also outputs an IMU message when heading information from GPS is available (in a moving base configuration).
This PR however aims at the IMU message from integrated inertial sensors for which I don't have any experience using them. So I'll also leave this for the maintainers to review.

**Comment by riebl** [comment]
I have been hoping this PR would be included in the next release. Are there any blocking issues with my PR @versatran01?

**Comment by versatran01** [comment]
@riebl If you are confident that this is correct then I will merge this.

**Comment by riebl** [comment]
@versatran01 Yes, I am confident about my PR. I have checked it with an M8U and the reported IMU data is now complying with ROS' conventions.

**Comment by Timple** [comment]
We don't use the internal imu so I'm unable to test this. But this PR looks better than the initial commit.

The melodic sync just happened, so I can trigger a release by the end of this week to make sure it will make the next one.

**Comment by versatran01** [comment]
@riebl great, I will merge this.
@Timple sounds good.

**Comment by Timple** [comment]
https://github.com/ros/rosdistro/pull/25331

**Pull request merged**
